# Generated by Django 3.1.2 on 2020-11-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('anio', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_direccion', models.TextField(verbose_name='Dirección: ')),
            ],
        ),
        migrations.CreateModel(
            name='LineaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.TextField(max_length=100)),
                ('precio_unitario', models.IntegerField(default=1)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factura.factura')),
            ],
        ),
    ]
