# Generated by Django 3.1.2 on 2020-11-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='unidades',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
