# Generated by Django 3.1.2 on 2020-11-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_auto_20201109_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_direccion',
            field=models.TextField(max_length=100, verbose_name='Dirección: '),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cliente_nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre del cliente'),
        ),
    ]
