# Generated by Django 3.1.2 on 2020-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20201110_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
