# Generated by Django 3.1.2 on 2020-11-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_auto_20201114_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
