# Generated by Django 3.1.2 on 2020-11-14 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20201114_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.DateTimeField(verbose_name=datetime.datetime.now),
        ),
    ]
