# Generated by Django 3.1.2 on 2020-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20201114_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
